name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        config-inline: |
          [registry."185.217.125.52:5000"]
            http = true
            insecure = true
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cicd_clem:latest
        docker tag cicd_clem 185.217.125.52:5000/cicd_clem:latest
        docker push 185.217.125.52:5000/cicd_clem:latest
