name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        set DOCKER_BUILDKIT=0
        docker build . --file Dockerfile --tag cicd_clem:latest
        docker tag cicd_clem http://185.217.125.52:5000/cicd_clem:latest
        docker push http://185.217.125.52:5000/cicd_clem:latest
