name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Insecure Docker Repository
      run: |
        sudo truncate -s-2 /etc/docker/daemon.json
        echo ", \"insecure-registries\": [\"185.217.125.52:5000\"]}" | sudo tee -a /etc/docker/daemon.json
        sudo systemctl restart docker
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        IP_SECRET: ${{ secrets.ip }}
      run: |
        docker build . --file Dockerfile --tag cicd_clem:latest
        docker tag cicd_clem "$IP_SECRET":5000/cicd_clem:latest
        docker push "$IP_SECRET":5000/cicd_clem:latest
